export const products = [
  { id : 1,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 100,
    discount: 20,
    image: "https://s8.uupload.ir/files/download_mw87.jpg",
    quantity : 1,
  },
  { id : 2,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 90,
    discount: 30,
    image: "https://s8.uupload.ir/files/download(2)_c1g.jpg",
  },
  { id : 3,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 80,
    discount: 40,
    image: "https://s8.uupload.ir/files/download_(1)_i6k4.jpg",
  },
  { id : 4,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 120,
    discount: 0,
    image: "https://s8.uupload.ir/files/images_nj3n.jpg",
  },
  { id : 5,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 110,
    discount: 10,
    image: "https://s8.uupload.ir/files/download_mw87.jpg",
  },
  { id : 6,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 220,
    offPrice: 120,
    discount: 100,
    image: "https://s8.uupload.ir/files/download(2)_c1g.jpg",
  },
  { id : 7,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 220,
    offPrice: 170,
    discount: 0,
    image: "https://s8.uupload.ir/files/download_(1)_i6k4.jpg",
  },
  { id : 8,
    name: "Adidas",
    descreption: [
      { support: "گارانتی مادالم العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 120,
    discount: 0,
    image: "https://s8.uupload.ir/files/images_nj3n.jpg",
  },

];
